---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prometheus
  annotations:
    "openshift.io/display-name": Prometheus
    iconClass: fa fa-cogs
    tags: "monitoring, prometheus, time-series"
parameters:
  - description: The location of the prometheus image
    name: IMAGE_PROMETHEUS
    value: quay.io/prometheus/prometheus:v2.17.1
  - name: APPLICATION_NAME
    value: prometheus-demo

objects:
  - apiVersion: v1          # Click on 'Copy to Editor' --->
    kind: ConfigMap
    metadata:
      name: prometheus-demo
      namespace: pad-monitoring
    data:
      prometheus.yml: |
        global:
          external_labels:
            monitor: prometheus
        scrape_configs:
          - job_name: 'prometheus'

            static_configs:
              - targets: ['localhost:9090']
                labels:
                  group: 'prometheus'

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        deploymentConfig: ${APPLICATION_NAME}
        app: ${APPLICATION_NAME}
    spec:
      replicas: 1
      selector:
        deploymentConfig: ${APPLICATION_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentConfig: ${APPLICATION_NAME}
            app: ${APPLICATION_NAME}
        spec:
          containers:
            - name: ${APPLICATION_NAME}
              args:
                - --storage.tsdb.path=/data
                - --storage.tsdb.retention.time=4w
                - --storage.tsdb.min-block-duration=2h
                - --storage.tsdb.max-block-duration=2h
                - --config.file=/etc/prometheus/prometheus.yml
                - --web.listen-address=0.0.0.0:9090
              image: ${IMAGE_PROMETHEUS}
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /etc/prometheus
                  name: prometheus-config
                - mountPath: /data
                  name: prometheus-data
          restartPolicy: Always
          volumes:
            - name: prometheus-config
              configMap:
                defaultMode: 420
                name: ${APPLICATION_NAME}
            - name: prometheus-data
              persistentVolumeClaim:
                claimName: ${APPLICATION_NAME}

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "10Gi"

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}-service
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - port: 9090
          name: http
      selector:
        app: ${APPLICATION_NAME}

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: ${APPLICATION_NAME}-route
      labels:
        app: ${APPLICATION_NAME}
    spec:
      to:
        kind: Service
        name: ${APPLICATION_NAME}-service
