(function(){var d=void 0,g=true,i=null,j=false;function k(){return function(){}}function m(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,r=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function da(a,b,c){if(!a)throw Error();if(arguments.length>2){var e=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,e);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:da;return s.apply(i,arguments)}function ea(a,b){function c(){}c.prototype=b.prototype;a.la=b.prototype;a.prototype=new c;a.prototype.constructor=a};function fa(){}
function ga(a,b,c){switch(typeof b){case "string":ia(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==i){c.push("null");break}if(aa(b)=="array"){var e=b.length;c.push("[");for(var f="",h=0;h<e;h++)c.push(f),ga(a,b[h],c),f=",";c.push("]");break}c.push("{");e="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(h=b[f],typeof h!="function"&&(c.push(e),ia(f,c),c.push(":"),ga(a,h,c),e=","));
c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var la={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"},ma=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;function ia(a,b){b.push('"',a.replace(ma,function(a){if(a in la)return la[a];var b=a.charCodeAt(0),f="\\u";b<16?f+="000":b<256?f+="00":b<4096&&(f+="0");return la[a]=f+b.toString(16)}),'"')};var na={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3};function oa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function pa(a,b){var c="",e=qa(encodeURIComponent(a));e.splice(b||5,e.length);t(e,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",e;a>0;)e=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(e)+b,a>>>=6;a=b}c+=a});return c}
function qa(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,e=4023233417,f=2562383102,h=271733878,l=3285377520,o=[],n,D,G,R,U,ha=Math.ceil((a.length/4+2)/16),ca=[ha],N=0,E;N<ha;N++){ca[N]=[];for(n=0;n<16;n++)ca[N][n]=a.charCodeAt(N*64+n*4)<<24|a.charCodeAt(N*64+n*4+1)<<16|a.charCodeAt(N*64+n*4+2)<<8|a.charCodeAt(N*64+n*4+3)}N=(a.length-1)*8;a=ha-1;ca[a][14]=Math.floor(N/Math.pow(2,32));ca[a][15]=N&4294967295;for(N=0;N<ha;N++){for(E=0;E<16;E++)o[E]=
ca[N][E];for(E=16;E<80;E++)o[E]=(o[E-3]^o[E-8]^o[E-14]^o[E-16])<<1|(o[E-3]^o[E-8]^o[E-14]^o[E-16])>>>31;a=c;n=e;D=f;G=h;R=l;for(E=0;E<80;E++)U=Math.floor(E/20),U=(a<<5|a>>>27)+(U==0?n&D^~n&G:U==1?n^D^G:U==2?n&D^n&G^D&G:n^D^G)+R+b[U]+o[E]&4294967295,R=G,G=D,D=n<<30|n>>>2,n=a,a=U;c=c+a&4294967295;e=e+n&4294967295;f=f+D&4294967295;h=h+G&4294967295;l=l+R&4294967295}return[c,e,f,h,l]}
function ra(a){var b=r.navigator,c=r.window.screen,e=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];t(b.plugins,function(a){e.push(a.name+a.description+a.filename+a[0].type)});b=r.performance;e=e.concat([b&&b.now?b.now():"",document.title,r.location.href,u(),oa()]);return e.concat(a||[]).join()}function v(a,b,c){var e=Array.prototype.slice,f=e.call(arguments,2);return function(){return a.apply(b,f.concat(e.call(arguments)))}}
function w(a){return typeof a!=="undefined"}function x(a){return a&&a.replace(/^www\./,"")}var sa=/^((https?\:)?(\/\/))/i;function ta(a){return a&&a.replace(sa,"")}var ua=/^((https?\:)?(\/\/))?[^\/]*/;function va(a){return a.replace(ua,"")}var wa=/\#.*/;function xa(a){return a.replace(wa,"")}var za=/\?[^\#]*/;function Aa(a){return a.toLowerCase()}var Ba=/\/+((\?|\#).*)?$/;function Ca(a){return a.replace(Ba,"$1")}function Da(a){return a&&a.replace(za,"")}
function Ea(a){var b=a.match(/\?(.*)$/ig)?a.match(/\?(.*)$/ig)[0].slice(1).replace(/#(.*)?/ig,"").split("&"):[],c=a.match(/#(.*)$/ig)?a.match(/#(.*)$/ig)[0]:"",a=a.match(/[#|\?](.*)?/ig)?a.slice(0,a.search(/[#|\?](.*)?/ig)):a,b=Fa(b,function(a){return a.search("utm")!==0});b.length>0&&(a+="?"+b.join("&"));return a+c}function Ga(a,b){if(a===b)return 0;var c=i;t([Aa,Ca,ta,va,xa,Da],function(e,f){a=e(a);b=e(b);if(a===b)return c=f+1,j});return c}
function Ha(a,b,c,e){a.addEventListener?a.addEventListener(b,c,!!e):a.attachEvent&&a.attachEvent("on"+b,c)}function Ia(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function Ja(a){return typeof a==="number"}function Ka(a){return typeof a==="string"}function La(a){return typeof a==="function"}function Ma(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function u(){return(new Date).getTime()}
function Na(a){return encodeURIComponent(a)}function Oa(){return r.location.protocol==="http:"?"http:":"https:"}function Pa(a){return!!a&&a.constructor===Object}function t(a,b){if(Pa(a)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var e=a.length;c<e;c++)if(b(a[c],c)===j)break}}function Qa(a,b){for(var c=0,e=a.length;c<e;c++)if(b(a[c]))return c;return-1}function Ra(a){var b=r.pSUPERFLY_video,a=Qa(b,a);if(a>-1)return b[a]}
function Fa(a,b){var c=[];t(a,function(a){b(a)&&c.push(a)});return c}function Sa(a){return a===d?0:u()-a}function Ta(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],e=0,f=b.length;e<=f;e++)c[e]=[e];for(var h=0,l=a.length;h<=l;h++)c[0][h]=h;for(var o,n,D,e=1;e<=f;e++)for(h=1;h<=l;h++)o=e-1,n=h-1,D=c[o][n],b.charAt(o)==a.charAt(n)?c[e][h]=D:(n=c[e][n]+1,o=c[o][h]+1,D+=2,c[e][h]=Math.min(n,o,D));return c[b.length][a.length]}
function Ua(a){return a===d?0:u()-a}function y(a){return Math.round(a===-1||isNaN(a)?-1:a*1E3)}var Va;function Wa(){}var Xa=r.setInterval,Ya=r.clearInterval,Za=r.setTimeout,$a=r.clearTimeout;function ab(a,b){return Xa(a,b)}function bb(a){switch(a){case d:return"undefined";case "":return"empty";default:return a}}function cb(a){switch(a){case "undefined":break;case "empty":return"";default:return a}};function db(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace(/\+/g," "),t(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function eb(a,b){var c="",e=r.location.href.match(/[^?]+[?]([^#]+).*/);if(e){var e=db(e[1]),f=b||a;e[f]&&(c=e[f])}return encodeURIComponent(c)}function fb(a,b){return!b?g:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function gb(a){var b=[];t(hb,function(c){var e=a[c];w(e)&&(Object.prototype.toString.call(e)==="[object Array]"?t(e,function(a){b.push(c+"="+a)}):Pa(e)?t(e,function(a,c){b.push(c+"="+a)}):((e+"").length||c=="r")&&b.push(c+"="+e))});b.push("_");return b.join("&")}
function ib(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),e=r.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0&&a.indexOf("app:")<0)if(a.indexOf("//")===0)a=e.protocol+a;else if(a.indexOf("/")===0)var f=fb(e.protocol,e.port)?"":e.port,a=e.protocol+"//"+e.hostname+(f?":"+f:"")+a;else{var f=document.baseURI||e.href,h=f.indexOf("?");h===-1&&(h=f.indexOf("#"));if(h===-1)h=f.length;h=f.lastIndexOf("/",h);a=h===-1?
"/"+a:f.substr(0,h)+"/"+a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=e.hostname;if(b.protocol==="")b.protocol=e.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(fb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function jb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash};function kb(a,b,c,e){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+(a+(e?'="'+e+'"':""))+"]");for(var f=[],b=c.getElementsByTagName(b),c=b.length,h="";c--;)(h=b[c].getAttribute(a))&&(!e||h===e)&&f.push(b[c]);return f}function lb(a,b,c){c=c||"";if(a===d)a=j;else{var e;if(!(e=c===""&&a.getAttribute(b)))if(e=a.getAttribute(b))e=a.getAttribute(b)===c;a=e?a:a===document.body?j:lb(a.parentNode,b,c)}return a}
function mb(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=kb("data-cb-scroll-element"))&&a.length)return a[0][c];if(Ja(r[b]))return r[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function nb(){var a=document,a=a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0;window.innerHeight&&(a=Math.min(window.innerHeight,a));return a}
function ob(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function pb(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var e=a.ownerDocument.documentElement,f=0,h=w(c)?c+1:-1;Ka(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==e&&f!==h;){if(c(a))return a;a=a.parentNode;f++}return i}
function qb(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}function rb(a){a=a||window.event;return!a?i:pb(a.target||a.srcElement,qb,10)}function sb(a,b){var c=document.createElement(a);t(b,function(a,b){c.setAttribute(b,a)});return c}function tb(){return r.document.readyState==="complete"||r.document.readyState!=="loading"&&!r.document.documentElement.doScroll}
function ub(a){function b(){if(r.document.addEventListener||r.event.type==="load"||r.document.readyState==="complete")r.document.addEventListener?(r.document.removeEventListener("DOMContentLoaded",b,j),r.removeEventListener("load",b,j)):(r.document.detachEvent("onreadystatechange",b),r.detachEvent("onload",b)),a()}tb()?a():r.document.addEventListener?(r.document.addEventListener("DOMContentLoaded",b,j),r.addEventListener("load",b,j)):(r.document.attachEvent("onreadystatechange",b),r.attachEvent("onload",
b))};function vb(){this.oa={};this.Ya=1}function wb(a,b,c,e){a.Ya++;a.oa[b]=a.oa[b]||{};a.oa[b][a.Ya]=[c,e];return a.Ya}function xb(a,b){if(Ka(b))a.oa[b]=d,delete a.oa[b];else if(Ja(b)){var c=g;t(a.oa,function(a){t(a,function(f,h){if(parseInt(h,10)===b)return a[h]=d,delete a[h],c=j});return c})}}vb.prototype.Ja=function(a,b){if(this.oa[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];t(this.oa[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
vb.prototype.addEventListener=function(a,b){var c=wb(this,a,b);b._cbEventId=c};vb.prototype.removeEventListener=function(a,b){this.oa[a]&&this.oa[a][b._cbEventId]&&this.oa[a][b._cbEventId][0]===b&&xb(this,b._cbEventId)};var z=new vb;var A={};
A.da=function(){A.Xb?A.Bb("pageload"):(A.hd=[{target:r,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:r,event:"resize"},{target:document.body,event:"mousedown"}],A.Hb=i,A.Va=i,A.Wb={},A.Lc={},t(A.hd,function(a){var b=a.event;Ha(a.target,b,function(a){A.Bb.call(A,b,a)})}),wb(z,"f",function(){A.Bb("focus")}),A.Bb("pageload"),Ha(document.body,"click",function(a){(a=rb(a))&&z.Ja("c",a)},g),Ha(document.body,"contextmenu",function(a){(a=rb(a))&&z.Ja("r",
a)}),A.Xb=g)};A.nd=function(){var a,b=A.Lc.keydown;if(b===d)return j;b=u()-b;return b<=(a||15E3)&&b>=0};A.yc=100;A.Bb=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}A.ze(a);if(A.Hb===i)A.$c(a);else if(!A.Va||na[A.Va]<na[a])A.Va=a};A.ze=function(a){A.Lc[a]=u()};A.$c=function(a){A.Hb=Za(A.vd,A.yc);z.Ja("a");A.Wb[a]!==i&&$a(A.Wb[a]);A.re(a)};
A.re=function(a){var b=A.Wb;b[a]=Za(function(){$a(b[a]);delete b[a];var c=j;t(b,function(){c=g;return j});c||z.Ja("i")},na[a]+A.yc)};A.vd=function(){$a(A.Hb);A.Hb=i;if(A.Va)A.$c(A.Va),A.Va=i};var yb,zb,Ab,Bb,Cb;(function(){var a,b;t(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof r.document[a]==="boolean")return b=c,j});b!==d&&(Bb=a,Cb=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Ab=b+"visibilitychange")})();var Db=j;function Eb(){Db=Cb&&r.document[Cb]==="prerender"?g:j}function Fb(){zb=g;z.Ja("f")}function Gb(){zb=j;z.Ja("b")}
function Hb(a,b,c){r.addEventListener?r.addEventListener(a,c,j):r.document.attachEvent&&r.document.attachEvent(b,c)}function Ib(){var a=g;r.document.hasFocus&&(a=r.document.hasFocus());var b=j;Bb&&(b=r.document[Bb]);return a&&!b}function Jb(){Ib()?Fb():Gb()}function Kb(a){Eb();if(Db){var b=j,c=function(){b||(Eb(),Db||(b=g,a(),r.window.setTimeout(function(){r.document.removeEventListener(Ab,c,j)},100)))};r.document.addEventListener(Ab,c,j)}else a()};function Lb(){this.k=r._sf_async_config||{};this.Gc=v(this.Sc,this)}Lb.prototype.da=function(){this.hb=0};Lb.prototype.Sc=k();Lb.prototype.ib=function(a){if(!Db){var b=this.Gc,c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}};Lb.prototype.Aa=function(){this.Gc=i};var B="path",C="domain",Mb="useCanonical",Nb="useCanonicalDomain",Ob="title",Pb="virtualReferrer";function F(a,b,c){a[b]=a[b]||c}function Qb(a,b){for(var c=r[a]||[];c.length;)b(c.shift());r[a]={push:b}}function Rb(a){t(document.getElementsByTagName("script"),function(b){if(typeof b.src==="string"&&b.src.match(/chartbeat.js/))return b=db(b.src.split("?")[1]),F(a,"uid",b.uid),F(a,C,b.domain),j})}function Sb(a,b){return a[b]?encodeURIComponent(a[b]):""}
function Tb(a){var b={};t(a,function(a,e){e.charAt(0)=="_"&&(b[e]=a)});return b};var H={};H.qd=function(a){try{H.create("_cb_test","1",1,a);var b=H.D("_cb_test");H.remove("_cb_test",a);return b==="1"}catch(c){return j}};H.D=function(a){a+="=";var b="";t(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
H.create=function(a,b,c,e){var f=r._sf_async_config;if(f&&f.noCookies)return"";f=new Date;f.setTime(u()+c*1E3);a=a+"="+b+("; expires="+f.toGMTString())+("; path="+e);return document.cookie=a};H.remove=function(a,b){return H.D(a)?H.create(a,"",-86400,b):""};var I={};I.ea=function(a){var b=r._sf_async_config;if(!a&&b&&b.noCookies)return i;if(I.ea.Nb!==d)return I.ea.Nb;var a=u()+"",c,e;try{if((e=r.localStorage).setItem(a,a),c=e.getItem(a)===a,e.removeItem(a),c)return I.ea.Nb=e}catch(f){}return I.ea.Nb=i};I.D=function(a){var b=I.ea();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&u()>c)?(I.remove(a),""):b.getItem(a)||""};
I.create=function(a,b,c){var e=I.ea();if(e){var f=new Date;f.setTime(u()+c*1E3);try{e.setItem(a,b),e.setItem(a+"_expires",f.getTime())}catch(h){}}};I.remove=function(a){var b=I.ea();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ub(a,b){this.Db=a||"";this.za=b||"/";this.wd=I.ea()!==i||H.qd(this.za);this.sc=j;Vb(this)}q=Ub.prototype;q.isSupported=m("wd");
function Vb(a){if(!H.D("_cb_ls")){var b=I.ea()!==i,c=H.D("_SUPERFLY_lockout");c&&t(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,g)});var e=H.D("_chartbeat3");e&&(a.create("_v__chartbeat3",e,34128E3,g),H.remove("_chartbeat3",a.za));b&&((b=H.D("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,g),(b=H.D("_chartbeat5"))&&a.create("_chartbeat5",b,60,g));H.create("_cb_ls","1",34128E3,a.za)}}function Wb(a){var b=a.sc;a.sc=j;return b}
q.create=function(a,b,c,e){a=e?a:this.Db+a;(I.ea()?I:H).create(a,b,c,this.za);I.ea()&&H.create(a,b,c,this.za)};q.update=function(a,b,c,e,f,h,l){a=e?a:this.Db+a;f=Ka(f)?f:"::";e=(e=this.D(a,g))?e.split(f):[];if(l&&e.length){var o=l(b),n=Qa(e,function(a){return l(a)===o});n!==-1&&e.splice(n,1)}e.push(b);for(Ja(h)&&e.length>h&&e.splice(0,e.length-h);e.length>1&&e.join(f).length>4E3;)e.shift();this.create(a,e.join(f),c,g)};
q.D=function(a,b){var a=b?a:this.Db+a,c=(I.ea()?I:H).D(a);if(!c&&I.ea()&&(c=H.D(a))&&H.D("_cb_ls")){this.sc=g;var e;switch(a){case "_SUPERFLY_lockout":e=600;break;case "_chartbeat4":e=60;break;case "_cb_cp":e=60;break;case "_chartbeat3":e=34128E3;break;default:e=34128E3}I.create(a,c,e)}return c};q.remove=function(a,b){a=b?a:this.Db+a;(I.ea()?I:H).remove(a,this.za);I.ea()&&H.remove(a,this.za)};function Xb(a){var b=i;if(a&&(b=Yb(),b=!b?b:J(b.pathname)+b.search+b.hash))return b;var c=r.location,b=J(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),e=/&utm_[^=]+=[^&]+/ig;(c=e.exec(c.search))&&(a=a.replace(e,""));e=/\?utm_[^=]+=[^&]+(.*)/i;(c=e.exec(a))&&(a=a.replace(e,c[1]!=""?"?"+c[1]:""));return b+a}function Zb(a){return a&&(a=Yb(),a=!a?a:a.hostname)?a:r.location.hostname}function Yb(){var a=$b();return!a?a:ib(a.href)}
function $b(){var a=i;t(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return a=b,j});return a}for(var ac={},bc=0;bc<81;bc++)ac["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(bc)]=g;function cc(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return ac[c]?String.fromCharCode(c):"%"+b.toUpperCase()}
function J(a){if(!Ka(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,cc);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function dc(a,b){var c=ec();return w(b)&&!w(c[a])?b:c[a]}function ec(){w(r._cb_shared)||(r._cb_shared={});return r._cb_shared};var K={kd:{IDLE:0,Ee:1,De:2,jd:3},sa:0};K.da=function(){if(!K.Xb)wb(z,"a",K.Dd,K),wb(z,"i",K.Gd,K),wb(z,"f",K.Fd,K),wb(z,"b",K.Ed,K),K.Xb=g};K.H=function(){return K.sa};K.Dd=function(){K.sa===1?K.Fa(3):K.sa===0&&K.Fa(2)};K.Gd=function(){K.sa===3?K.Fa(1):K.sa===2&&K.Fa(0)};K.Fd=function(){(K.sa===0||K.sa===2)&&K.Fa(3)};K.Ed=function(){K.sa===3?K.Fa(2):K.sa===1&&K.Fa(0)};K.Fa=function(a){K.sa=a;z.Ja("s",a)};function fc(a,b){this.Vb=a||d;this.dc=b||d;this.ab=this.Xa=0;this.Ld=v(this.Md,this);this.bd=this.Wa=i}q=fc.prototype;q.da=function(){this.ab=this.Xa=0;this.Wa=i;this.bd=wb(z,"s",this.Kc,this);this.Kc(K.H())};q.Kc=function(a){Ya(this.Wa);this.Wa=i;if(a===K.kd.jd)this.Wa=Xa(this.Ld,1E3)};q.Md=function(){if(this.Vb===d||this.Vb())this.Xa++,this.ab++,this.dc&&this.dc()};q.terminate=function(){Ya(this.Wa);this.Wa=i;xb(z,this.bd)};q.Aa=function(){this.terminate();this.dc=this.Vb=d};function gc(){Lb.call(this);this.Ma=[];this.B=new Ub(this.cd,this.k.cookiePath||"/");this.B.remove("_SUPERFLY_nosample");this.na=new fc;this.gc=v(this.fb,this);Ha(r,"unload",this.gc);this.xb=j;hc(v(this.da,this))}ea(gc,Lb);function hc(a){ub(function(){Kb(a)})}q=gc.prototype;q.pc=g;q.ic=j;
q.da=function(){gc.la.da.call(this);this.vb=this.Pa=0;this.Ua=u();this.Ea=pa(ic(this));this.mc=g;this.yb=72E5;if(this.pc){var a=+this.k.sessionLength;if(!isNaN(a))this.yb=a*6E4}a=dc("d");if(!a){var a=[],b=this.B.D("_chartbeat2",g);b.length>0&&(a=b.split("."));a.length>6&&(a=[]);var b=u(),c=this.B.D("_cb",g);c.length>0?a[1]=a[1]||b:c=a[0];a[0]="";var e=b-+(a[1]||0),f=b-+(a[2]||0);ec().n=c&&e>18E5&&f<2592E6?0:1;var e=a[4],h=parseInt(a[5],10)||0;if(!(f=f>18E5))if(jc(this))f=j;else{var f=kc(this),f=decodeURIComponent(f),
f=lc(f)||f,l;l=mc(this);l=decodeURIComponent(l);l=lc(l)||l;f=f!==l}!e||f?(e=pa(ic(this)),a[4]=e,h=1,this.B.remove("_cb_svref",g)):h+=1;a[5]=h;h="1";f=a&&+a[2];e=a&&a[3];if(a&&f&&e)if(h=Math.abs((Ma(b)-Ma(f))/864E5)){h=Math.min(h,16)-1;for(f="";h--;)f+=0;h=(e+f+"1").slice(-16)}else h=e;e=h;c||(c=this.k.utoken||pa(ic(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.kb;this.B.create("_cb",c,34128E3,g);this.B.create("_chartbeat2",a.join("."),34128E3,g);a[0]=c;ec().d=a}this.Le=a.join(".");var o;c=+a[1];
e=+a[2];if((b=a[3])&&c&&e)o=(Math.min((Math.abs((Ma(e)-Ma(c))/864E5)||0)+1,16,b.length)-1).toString(16),o+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Jc=o;this.$b=dc("n",1);this.kb=a[0];this.ve=a[4];this.te=a[5];this.ue=mc(this);this.B.create("_cb_svref",mc(this)||"null",1800,g);this.na.da();K.da();A.da();yb||(zb=Ib(),Ab&&r.document.addEventListener&&r.document.addEventListener(Ab,Jb,j),Hb("focus","onfocusin",Fb),Hb("blur","onfocusout",Gb),zb&&Fb(),yb=g);this.cb=0;this.md=wb(z,"a",this.Qd,
this);this.ic=g;if(this.ec)Za(this.ec,0),this.ec=i};q.nb=function(){if(!this.B.D("_SUPERFLY_lockout"))this.ic?!tb()&&!this.xb?(this.Cb=v(this.rc,this),Ha(r,"load",this.Cb)):this.rc():this.ec=v(this.nb,this)};q.rc=function(){this.gb=nc();A.da();this.ub=ab(v(this.qa,this),15E3);this.qa()};
q.qa=function(){var a=this.na.ab,a=this.k.reading&&+this.k.reading||a>0;if(this.vb<this.Pa&&!a)this.vb++;else{var b;if(Va===d)b=r.navigator.userAgent,Va=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=Va;b&&!a?this.vb++:(a?this.Pa=0:this.Mb(),this.vb=0,this.Ma.push(0),this.Ma.length>18&&this.Ma.shift(),this.pc&&u()-this.Ua>=this.yb?this.terminate():this.Ca())}};
q.Sc=function(){this.Ma.push(1);var a=0;t(this.Ma,function(b){a+=b});a<3?(this.mc=g,this.Mb()):(this.terminate(),this.B.create("_SUPERFLY_lockout","1",600))};q.fb=k();q.Qd=function(){var a=oc(this);this.cb=Math.max(this.cb,a)};function oc(a){return Math.floor(mb(!!a.k.scrollElement))}q.Mb=function(){var a=this.Pa;this.Pa=a=a?Math.min(a*2,16):1};q.sb=function(){this.fb();this.terminate()};q.Fb=function(){this.xb=g;this.ic=j;this.da();this.nb()};
function jc(a){if(a.k[Pb])return g;if(pc(a))return j;a=document.referrer.indexOf("://"+r.location.hostname+"/");return a!=-1&&a<9}function pc(a){var b=a.k.referrerOverrideQueryParam,c="";t(window.location.search.substr(1).split("&"),function(a){a=a.split("=");if(a.length==2&&a[0]==b&&a[1])return c=decodeURIComponent(a[1]).replace(/\+/g," "),j});c&&c.indexOf("::")==-1&&(c="external::"+c);return c}
function kc(a){a=a.k[Pb]||pc(a);if(!a&&(a=document.referrer||"")&&!/^(android-)?app:/.test(a)){var b=ib(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=J(b.pathname),a=jb(b)}return encodeURIComponent(a)}function qc(a){a=a.k[Ob].slice(0,100);return encodeURIComponent(a)}function ic(a){a=[kc(a),ob("Width"),ob("Height")];return ra(a)}function rc(a){var b=[],c=a.B.D("_chartbeat4");c&&(t(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.B.remove("_chartbeat4"));return b}
function mc(a){a=a.B.D("_cb_svref",g)||kc(a)||"null";a==="null"&&(a="");return a=a.substr(0,128).replace(/%.?$/,"")}function lc(a){a=a.match(/^https?:\/\/([^\/]*)/);return!a?i:a[1]}function nc(){var a=r.performance&&r.performance.timing;if(!a||a.navigationStart==0)return-1;var b=a.navigationStart,a=a.loadEventStart;return Ja(b)&&b?Ja(a)&&a>b?a-b:u()-b:-1}q.terminate=function(){this.na.terminate();xb(z,this.md);this.Cb!==d&&Ia(r,"load",this.Cb);Ya(this.ub);ec().d=d;ec().n=d};
q.Aa=function(){this.terminate();Ia(r,"unload",this.gc);this.gc=this.Cb=this.B=this.Ma=this.k=i;this.na.Aa();this.na=i;gc.la.Aa.call(this)};function sc(a){for(var b=dc("m")||[];b.length;)a(b.shift());a={push:a};ec().m=a};function tc(a){var b=a.offsetLeft,c=a.offsetTop,e=uc(a);b+=e.x;c+=e.y;for(var f=j,e=a.offsetParent;a&&a!==d&&a!==document.body;){if(a===e)e=uc(a),b+=a.offsetLeft+e.x,c+=a.offsetTop+e.y,e=a.offsetParent;if(vc(a,["position"]).position==="fixed"){f=g;break}a=a.parentElement}f&&(b+=0,c+=0);return{x:b,y:c}}
function vc(a,b){var c={},e,f;r.getComputedStyle?e=r.getComputedStyle(a,i):a.currentStyle?f="currentStyle":a.style&&(f="style");t(b,function(b){c[b]=e?e[b]||e.getPropertyValue(b):a[f][b]});return c}var wc=/matrix(3d)?\((.*)\)/;function uc(a){var b={x:0,y:0},a=vc(a,["transform"]).transform;if(!Ka(a))return b;var c=a.match(wc);if(!c)return b;var a=c[2].split(", "),e;w(c[1])?(c=12,e=13):(c=4,e=5);b.x=parseInt(a[c],10);b.y=parseInt(a[e],10);return b};function xc(){var a=r.location.href,a=a.replace(/-{2,}/g,"-"),a=ib(a);a.pathname=J(a.pathname);return a}
function yc(a){var b=H.D("_chartbeat6");if(!b)return i;var b=b.split("::"),c,e;if(b.length===1)c=b[0].split(","),e=0;else{var f,h=xc(),l=jb(h);t(b,function(a,b){var h=a.split(","),n=Ta(l,decodeURIComponent(h[0]));if(n===0)return c=h,e=b,j;if(f===d||n<f)f=n,c=h,e=b})}b.splice(e,1);a="_chartbeat6="+b.join("::")+zc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),h=decodeURIComponent(c[1]),o=c[2];c.splice(0,3);for(var n=c.length/3,D=0;D<n;D++){var G=D*3+2;a.push({Ie:b,origin:h,Qa:o,Ta:G<c.length?
c[G]:"",yd:c[D*3],Ae:c[D*3+1]})}return a}function zc(a){var b="",c;if(!Pa(a))return b;a.Pc&&(c=new Date,c.setTime(c.getTime()+a.Pc),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function Ac(a){var b=a.topStorageDomain,a=a[C],c=r.location.hostname;return b?b:Bc(c,a)?a:c.replace(/^www\./,"")}
function Bc(a,b){if(a===b)return g;for(var c=b.split("."),e=a.split(".");c.length;){if(e.length===0)return j;if(c.pop()!==e.pop())return j}return g}function Cc(a,b,c,e,f){this.Ad=a;this.zd=b;this.Be=c;this.Qa=e;this.Ta=f}function Dc(a){var b=a.d,c=i;if(b!==i){var e={};b.s&&t(b.s,function(a,b){e[b]=typeof a==="string"?{Bc:a,Ta:""}:{Bc:a.chosenVariant,Ta:a.specificLocation}});c={Zc:e,Qa:b.g,Oc:b.m}}return{status:a.s,data:c,code:a.c,message:a.m}};function Ec(a,b){for(var c=b||document.documentElement,e=[],f=i,h=a,l,o,n,D,G,R;h&&h!==c;){l=h.nodeName.toLowerCase();f=h;o=f.nodeName;if((h=h.parentNode)&&h!==document.documentElement){n=h.children;D=0;for(G=0,R=n.length;G<R;G++){if(f===n[G]){l+="["+(1+G-D)+"]";break}n[G].nodeName!==o&&D++}}e.unshift(l)}return e.join("/")};function Fc(){this.cd="_t_";this.Ec=this.ad=Wa;gc.call(this)}ea(Fc,gc);q=Fc.prototype;
q.da=function(){Fc.la.da.call(this);Rb(this.k);var a=!!this.k[Mb],b=Zb(!!this.k[Nb]&&a);F(this.k,"mabServer","mabping.chartbeat.net");F(this.k,Ob,document.title);F(this.k,C,b);this.k[B]=this.k[B]?J(this.k[B]):Xb(a);this.ma=x(b);this.k[C]=x(this.k[C]);this.ye=Ac(this.k);this.Za=this.wb=j;this.Hc=[];var c=this,a=yc({domain:"."+this.ye,Pc:6E4,path:"/"});if(a!==i)this.wb=g,t(a,function(a){c.Hc.push(new Cc(a.origin,a.yd,a.Ae,a.Qa,a.Ta))});this.Qc=0;this.Gb=i;sc(v(this.Kd,this))};
q.Ca=function(){var a=this.na.Xa,b=Gc(this),c,e=this;this.wb&&t(this.Hc,function(f){c=b+"&x="+f.zd+"&v="+f.Be+"&ml="+f.Qa+"&xo="+f.Ad+"&e="+a+"&sl="+f.Ta;e.ib(c)});!this.Za&&this.Gb&&Hc(this,this.Gb);this.Za=g};q.rc=function(){this.gb=nc();A.da();if(this.wb)this.ub=ab(v(this.qa,this),500);this.qa()};q.qa=function(){var a,b;this.Za?(a=this.na.Xa,b=this.Qc*15,a-b>=15&&(this.Ca(),this.Qc+=1),a>=45&&this.terminate()):this.Ca()};
function Gc(a){var b=a.k;return Oa()+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b[C])+"&p="+encodeURIComponent(b[B])+"&d="+encodeURIComponent(a.ma)+"&u="+a.kb+"&c="+Math.round((u()-a.Ua)/600)/100}q.fb=k();q.we=function(a){a=Dc(a);this.Za?Hc(this,a):this.Gb=a};
function Hc(a,b){var c=Gc(a),e=b.status,f=b.data;if(e=="s"&&f!==i){var h=v(a.ib,a);Pa(f.Zc)&&t(f.Zc,function(a,b){h(c+"&x="+b+"&v="+a.Bc+"&ml="+f.Qa+"&sl="+a.Ta+"&e=-1")});Object.prototype.toString.call(f.Oc)==="[object Array]"&&t(f.Oc,function(a){h(c+"&me=3&ml="+f.Qa+"&x="+a)})}else e=="e"&&a.ib(c+"&me="+b.code)}
q.Kd=function(a,b){for(var c=0,e=arguments.length;c<e;c++){var a=arguments[c],f=a.shift();f==="t"?this.we.apply(this,a):f==="v"?this.Yc.apply(this,a):f==="sv"?this.se.apply(this,a):f==="ev"&&this.Yc.apply(this,a)}};q.sb=function(){this.Ec();Fc.la.sb.call(this)};q.Fb=function(){ec().m=[];this.ad();Fc.la.Fb.call(this)};q.se=function(a){this.ad=a};q.Yc=function(a){this.Ec=a};q.terminate=function(){this.Je=d;this.Gb=i;this.Za=this.wb=d;Fc.la.terminate.call(this)};if(!H.D("cb_optout")&&!r.pSUPERFLY_mab){var Ic=new Fc,Jc={};Jc.evps=v(Ic.sb,Ic);Jc.svps=v(Ic.Fb,Ic);r.pSUPERFLY_mab=Jc;Ic.nb()};var Kc,Lc,Mc;
function Nc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0)){var b=a.substr(16),c=j;Oc();if(b!=="NONE")b.indexOf("HUD2.")===0?b=b.substr(5):b.indexOf("HUD3.")===0?(c=g,b=b.substr(5)):b="OLD",a="https://static.chartbeat.com/js/inpage.js",c?a="https://static2.chartbeat.com/frontend_ng/hud3/hud-inpage/hud-inpage-"+b+".js":b!=="OLD"&&(a="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+b+".js"),b=w(d)?d:{},b.src=a,a=sb("script",b),a.setAttribute("type",
"text/javascript"),b=document.head||document.getElementsByTagName("head")[0],w(d)?d.appendChild(a):b&&b.appendChild(a)}}function Oc(){$a(Lc);Lc=d;Ia(r,"message",Nc);Mc&&Mc.parentNode&&Mc.parentNode.removeChild(Mc);Mc=d};var Pc=/^https?:\/\/([^/]*\.)?chartbeat\.com\/publishing\/hud2\/launch\//;function Qc(){var a=r._sf_async_config&&r._sf_async_config.domain;if(a&&!Kc){Kc=g;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);Ha(r,"message",Nc);Lc=Za(Oc,1E4);var b=w(d)?d:{};b.src=a;a=sb("iframe",b);a.style.display="none";w(d)?d.appendChild(a):document.body&&document.body.appendChild(a);Mc=a}}
function Rc(){var a=I.ea(g);return a?(a.setItem("_cb_ip","1"),a.removeItem("_cb_hud_collapsed"),g):j}function Sc(a){/[\/.]chartbeat\.com$/.test(a.origin)&&String(a.data).indexOf("_cb_ip")==0&&Rc()&&(a.source.postMessage(1,a.origin),ub(Qc),Ia(r,"message",Sc))};function Tc(a,b){this.gd=b;this.fd=a[Mb];this.ed=a[Nb];this.Ba=a[B];this.Ia=a[Ob];this.Cc=a[C];this.Ce=a[Pb];this.Ac=(this.ra=Yb())?this.ra.hostname:"";this.ob=this.ra?J(this.ra.pathname)+this.ra.search+this.ra.hash:"";this.Xc=Xb(j);this.oe=Zb(j);var c=kb("property","meta",i,"og:url");this.eb=(this.Ra=c&&c.length?ib(c[0].content):i)?J(this.Ra.pathname)+this.Ra.search+this.Ra.hash:"";this.Pd=this.Ra?this.Ra.hostname:"";this.Rb=document.title||"";var e;if((c=kb("property","meta",i,"og:title"))&&c.length)e=
c[0].content;this.Ab=e;var f;if((e=kb("property","meta",i,"twitter:title"))&&e.length)f=e[0].content;this.jb=f;f=!!this.fd;e=this.fd!==d;var c=!!this.ed,h=this.ed!==d,l=!!this.ra,o;o=x(this.Ac);var n=x(this.oe);o=o===n;var n=!!this.eb,D=!this.ra?j:this.ob===this.eb,G=this.ob===this.Xc,R;R=this.ob;var U=Da(this.Xc);R=R===U;var U=!!this.Rb,ha=!!this.Ab,ca=!!this.jb,N=this.Rb===this.Ab,E=!this.jb?j:this.Rb===this.jb,ja=!this.Ab||!this.jb?j:this.Ab===this.jb,ka=!!this.Ia,ud=!!this.Ba,vd=this.Ba?this.Ba.charAt(0)!==
"/":j,wd=!this.ra?j:this.Ba===this.ob,xd=!this.eb?j:this.Ba===this.eb,yd=!this.ra?j:this.Cc===x(this.Ac),zd=!this.eb?j:this.Cc===x(this.Pd),Ad=!!this.gd,Bd=this.gd?j:!!this.Ce,Cd=Oa()==="https:",Dd=!!XMLHttpRequest,ya;this.Ba?(ya=Ea(this.Ba),ya=ya!==Da(ya)):ya=j;f=[f,e,c,h,l,o,n,D,G,R,U,ha,ca,N,E,ja,ka,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,ya];e=1;for(h=c=0;h<f.length;h++)c|=f[h]&&e,e<<=1;this.rd=("00000000"+c.toString(16)).slice(-8)};function Uc(){"postMessage"in window&&Ha(r,"message",v(this.Hd,this));gc.call(this);Qb("_cbq",v(this.Wc,this))}ea(Uc,gc);
Uc.prototype.da=function(){Uc.la.da.call(this);var a=this.kb;ec().u=a;a=this.Ea;ec().t=a;this.Od=new Tc(this.k,this.xb);this.Lb=i;Rb(this.k);var a=!!this.k[Mb],b=Zb(!!this.k[Nb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,Ob,document.title);F(this.k,C,b);this.k[B]=this.k[B]?J(this.k[B]):Xb(a);this.ma=x(b);this.k[C]=x(this.k[C]);this.od=wb(z,"c",this.Td,this);this.pd=wb(z,"r",this.Ud,this);this.Oa=i};Uc.prototype.ld=function(a){this.Lb=a};
Uc.prototype.fb=function(){this.B.update("_chartbeat4",["t="+this.Ea,"E="+this.na.Xa,"x="+oc(this),"c="+Math.round((u()-this.Ua)/600)/100,"y="+ob("Height"),"w="+nb()].join("&"),60,d,d,1)};var hb="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,_x,_y,_z,_s,t,V,z,i,L,tz,l,,sn,C,sv,sr,sd,im".split(",");q=Uc.prototype;
q.Ca=function(a){this.hb++;var b={};b.g=this.k.uid;b.g0=Sb(this.k,"sections")||"No%20Section";b.g1=Sb(this.k,"authors")||"No%20Author";b.g2=Sb(this.k,"zone");b.g3=Sb(this.k,"sponsorName");b.g4=Sb(this.k,"type");!this.k.noCookies&&this.B.isSupported()?b.n=this.$b:b.nc=1;b.c=Math.round((u()-this.Ua)/600)/100;b.E=this.na.Xa;var c=oc(this);this.cb=Math.max(this.cb,c);b.x=c;b.m=this.cb;b.y=ob("Height");b.o=ob("Width");b.w=nb();b.b=this.gb>0?this.gb:"";if(this.Jc&&!this.k.noCookies&&this.B.isSupported())b.f=
this.Jc;b[""]=Tb(this.k);b.t=this.Ea;b.V=120;b.tz=(new Date).getTimezoneOffset();b.sn=this.hb;b.sv=this.ve;b.sr=this.ue;b.sd=this.te;c=this.na.ab;b.h=encodeURIComponent(this.k[C]);b.p=encodeURIComponent(this.k[B]);b.u=this.kb;b.d=encodeURIComponent(this.ma);b.j=Math.round((this.Pa+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;A.nd()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=jc(this);if(this.mc){this.mc=j;if(c)this.Oa=Vc(this);b.i=qc(this);var e=this.k.hudTrackable;e!==d&&(b.L=e?"1":
"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.Oa){if(b.v=encodeURIComponent(this.Oa.path),b.K=Wc(this.Oa),this.Oa.ac>1)b.l1=this.Oa.ac}else b.v=kc(this);this.xb&&(b.vp=1)}else b.r=kc(this);c=bb(b.v);ec().v=c;c=bb(b.r);ec().r=c;b.A=this.Lb?this.Lb:"";b._c=eb("utm_campaign",this.k.campaignTag);b._m=eb("utm_medium",this.k.mediumTag);b._x=eb("utm_source",this.k.sourceTag);b._y=eb("utm_content",this.k.contentTag);b._z=eb("utm_term",this.k.termTag);b.im=this.Od.rd;this.k.idSync?
(c=[],ga(new fa,this.k.idSync,c),c=encodeURIComponent(c.join(""))):c="";b._s=c;b.z=rc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Wc(a):"";b.l=Wb(this.B)?1:"";this.na.ab=0;this.ib(Oa()+"//"+this.k.pingServer+"/ping?"+gb(b))};
q.Hd=function(a){var b=this.k,c=b.playerdomain||this.ma;if(ta(a.origin)===ta(c))if(c=a.data,Ka(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Wc(a));else if(c=="cbdata?"){var c="&u="+dc("u"),e="&t="+dc("t"),f="&v="+dc("v"),h="&r="+dc("r"),b="domain="+encodeURIComponent(b[C])+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b[B])+"&title="+qc(this)+"&referrer="+kc(this)+"&internal="+(jc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.ma)+
c+e+f+h+"&utoken="+this.kb;a.source.postMessage(b,"*")}};q.Wc=function(a){var b=a[0],a=a[1];if(b==="_demo"&&this.k._demo)this.k._demo=this.k._demo+"%2C"+a;else if(a!==this.k[b]&&(this.k[b]=a,this.Pa=0,this.hb>0&&!this.tb)){var c=this.hb,e=this;this.tb=Za(function(){e.tb=i;e.hb===c&&e.Ca()},1E3)}};function Xc(a){a=a.replace(/-{2,}/g,"-");a=ib(a);a.pathname=J(a.pathname);return a}q.Td=function(a){Yc(this,a,"c")};q.Ud=function(a){Yc(this,a,"r")};
function Yc(a,b,c){if(a.pc&&u()-a.Ua>=a.yb)a.terminate();else{var e=b.href||"",e=Xc(e);if(e.protocol.indexOf("http")===0){var f=e.hostname!==r.location.hostname,e=jb(e),h=pb(b,function(a){return a.id}),l=Ec(b,h),o="";a.k.moduleAttribute&&(o=(o=lb(b,a.k.moduleAttribute))?o.getAttribute(a.k.moduleAttribute):"",o=o.replace(/::/g,"-").substr(0,40));h?(l&&(l="/"+l),l="*[@id='"+h.id+"']"+l,h=Ec(b)):h=l;l=pa(l);h=pa(h);b=tc(b);c={left:b.x,top:b.y,path:a.k[B],href:e,xc:l,Kb:h,wc:"",qc:c,ac:0,Cd:a.k[C],Zb:o};
a.Ca(c);f||a.B.update("_chartbeat5",Zc(c),60,j,d,3,function(a){a=a.split(",");return a[2]+","+a[3]})}}}function Wc(a){return[a.left,a.top,a.xc,encodeURIComponent(a.wc),a.qc,encodeURIComponent(a.href),a.Kb,a.Zb].join("::")}function Zc(a){var b=encodeURIComponent(a.wc),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.xc,b,a.qc,a.Kb,encodeURIComponent(a.Cd),a.Zb].join(",")}
function Vc(a){var b=a.B.D("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,e,f=i,h,l=Xc(r.location.href),o=jb(l);t(c,function(a,b){var c=a.split(","),l=decodeURIComponent(c[3]);if(l){l=Ga(o,l);if(l===0)return e=c,f=b,j;else if(l===i)return g;if(h===d||l<h)h=l,e=c,f=b}});if(f===i)return i;c.splice(f,1);a.B.create("_chartbeat5",c.join("::"),60);(a=e[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:e[0],top:e[1],path:decodeURIComponent(e[2]),href:decodeURIComponent(e[3]),
xc:e[4]||"",wc:"",Kb:e.length>7?e[7]:"",qc:e.length>6?e[6]:"c",ac:b,Zb:e[9]?e[9]:""}}q.terminate=function(){xb(z,this.od);xb(z,this.pd);$a(this.tb);this.tb=i;Uc.la.terminate.call(this)};var L="ct",M="s1";function O(a){this.a=a;this.G=this.F=j;this.q=u();this.ga()}q=O.prototype;q.ga=function(){this.a.currentTime()>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.on("play",v(this.fa,this));this.a.on("dispose",v(this.Wd,this));this.a.ready(v(this.ka,this))};q.ka=function(){this.F=g};q.fa=function(){this.G=g};q.Wd=function(){var a=r._cbv;a&&a.push&&a.push(["removePlayer",this.a])};q.M=function(){return this.F&&this.N()!==""};
q.Tb=function(){var a;this.a.cb_configs&&this.a.cb_configs[C]?a=this.a.cb_configs[C]:!a&&r._sf_async_config&&r._sf_async_config[C]&&(a=r._sf_async_config[C]);return a};q.Ub=function(){var a;this.a.cb_configs&&this.a.cb_configs.uid?a=this.a.cb_configs.uid:!a&&r._sf_async_config&&r._sf_async_config.uid&&(a=r._sf_async_config.uid);return a};q.N=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("name")?a.name:this.a.el().getAttribute("title"))||""};
q.J=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("id")?a.id:this.a.el().attributes["data-video-id"]&&this.a.el().attributes["data-video-id"].value?this.a.el().attributes["data-video-id"].value:this.a.src())||""};q.T=function(){return L};q.O=p("");q.aa=function(){var a=this.a.duration();return y(a)};q.H=function(){return!this.G?M:this.a.ended()?"s4":this.a.paused()?"s3":"s2"};q.U=function(){var a=this.a.currentTime();return y(a)};q.S=p(-1);
q.$=function(){var a=this.a.mediainfo;return(a&&a.hasOwnProperty("thumbnail")?a.thumbnail:this.a.poster())||""};q.X=k();q.Q=k();q.ba=function(){return Ua(this.q)};q.Y=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.sections?a=this.a.cb_configs.sections.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.sections&&(a=r._sf_async_config.sections.split(","));if(a.length>0&&a[0]!=="")return a};
q.P=function(){var a=[];this.a.cb_configs&&this.a.cb_configs.authors?a=this.a.cb_configs.authors.split(","):a.length==0&&r._sf_async_config&&r._sf_async_config.authors&&(a=r._sf_async_config.authors.split(","));if(a.length>0&&a[0]!=="")return a};q.Z=p("BCN");O.prototype.getStrategyName=O.prototype.Z;O.prototype.isReady=O.prototype.M;O.prototype.getHost=O.prototype.Tb;O.prototype.getUid=O.prototype.Ub;O.prototype.getTitle=O.prototype.N;O.prototype.getVideoPath=O.prototype.J;
O.prototype.getContentType=O.prototype.T;O.prototype.getAdPosition=O.prototype.O;O.prototype.getTotalDuration=O.prototype.aa;O.prototype.getState=O.prototype.H;O.prototype.getCurrentPlayTime=O.prototype.U;O.prototype.getBitrate=O.prototype.S;O.prototype.getThumbnailPath=O.prototype.$;O.prototype.getPlayerType=O.prototype.X;O.prototype.getAutoplayType=O.prototype.Q;O.prototype.getViewStartTime=O.prototype.ba;O.prototype.getSections=O.prototype.Y;O.prototype.getAuthors=O.prototype.P;
O.verify=function(a){return a.controlBar!==d||a.cb_plugin_version!==d};function P(a){this.Ya=this.ma=d;this.F=j;this.Vc=this.Dc=-1;this.ua=i;this.a=a;this.G=j;this.hc=g;this.q=u();this.jc="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var e=a[c];if((e.indexOf("chartbeat")>=0||e.indexOf("localhost")>=0)&&e.indexOf(".js")>=0){this.jc=e;break}}if(this.jc){a=db(this.jc);if(this.ma=a[C])this.ma=this.ma.replace(/^video@/,"");this.Ya=a.uid}a=window.brightcove;this.a=a.api.getExperience();b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);
b.getReady()?this.Tc():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Tc,this))}q=P.prototype;
q.Tc=function(){var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.Dc=Math.round(a)});b.getCurrentVideo(function(a){c.ua=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.de,this));b.addEventListener(a.STOP,s(this.fe,this));b.addEventListener(a.COMPLETE,s(this.Vd,this));b.addEventListener(a.BEGIN,s(this.fa,this));this.F=g};q.de=function(a){this.Vc=a.position;this.ya=this.hc=j};q.fe=function(){this.hc=g};
q.Vd=function(){this.ya=g};q.fa=function(){this.ya=j;if(!this.G)this.G=g};q.M=m("F");q.N=function(){var a="";this.ua&&(a=this.ua.displayName);return a};q.J=function(){var a="";this.ua&&(a="video@"+this.ma+"/"+this.ua.id);return a};q.T=function(){return L};q.O=p("");q.aa=m("Dc");q.H=function(){return!this.G?M:this.ya?"s4":this.hc?"s3":"s2"};q.U=function(){return y(this.Vc)};q.S=p(-1);q.$=function(){var a="";this.ua&&(a=this.ua.thumbnailURL);return a};q.X=k();
q.ba=function(){return isNaN(this.q)?0:Sa(this.q)};q.P=k();q.Y=function(){var a;this.ua&&(a=this.ua.tags);return a};q.Q=p("unkn");q.Z=p("BC");q.Tb=m("ma");q.Ub=m("Ya");P.prototype.isReady=P.prototype.M;P.prototype.getTitle=P.prototype.N;P.prototype.getVideoPath=P.prototype.J;P.prototype.getContentType=P.prototype.T;P.prototype.getAdPosition=P.prototype.O;P.prototype.getTotalDuration=P.prototype.aa;P.prototype.getState=P.prototype.H;P.prototype.getCurrentPlayTime=P.prototype.U;
P.prototype.getBitrate=P.prototype.S;P.prototype.getThumbnailPath=P.prototype.$;P.prototype.getPlayerType=P.prototype.X;P.prototype.getViewStartTime=P.prototype.ba;P.prototype.getAuthors=P.prototype.P;P.prototype.getSections=P.prototype.Y;P.prototype.getAutoplayType=P.prototype.Q;P.verify=function(a){return a===window.brightcove};P.prototype.getStrategyName=P.prototype.Z;P.prototype.getHost=P.prototype.Tb;P.prototype.getUid=P.prototype.Ub;function Q(a){this.a=a;this.G=this.F=j;this.q=u();this.Nc=this.xa=this.Da=d;this.Ia=this.Ha="";this.Yb=d;this.ga()}var $c=/url\(['"]?([^'"\)]*)['"]?\)/;q=Q.prototype;
q.Sb=function(){var a=this.Nc=this.J();if(this.a.conf&&(this.Ia=this.a.conf.title?this.a.conf.title:"",this.Ha=this.a.conf.poster?this.a.conf.poster:"",this.Ia&&this.Ha))return g;var b=kb("name","param"),c=d;t(b,function(b){if(b.attributes.name&&b.attributes.name.value==="flashvars"&&b.value.indexOf(a)!==-1)return c=b,j});c===d&&(b=kb("src","video"),t(b,function(b){if(b.attributes.src.value&&a.indexOf(b.attributes.src.value)!=-1)return c=b,j}));b=lb(c,"data-swf")||lb(c,"poster");if(b===j)return j;
this.Ha=b.attributes.poster&&b.attributes.poster.value;if(!this.Ha){var e=b.style.background;if(e&&(e=e.match($c)))this.Ha=e[1]}this.Ia=b.title;if(this.Yb!==d)clearInterval(this.Yb),this.F=g;return g};function ad(a){if(a.Nc!==a.J())a.Ha="",a.Ia="",a.Sb()}q.ga=function(){this.a.ready?this.ka():this.a.bind("ready",s(this.ka,this));this.a.bind("resume",s(this.fa,this));this.a.playing&&this.fa()};q.ka=function(){this.Sb()===j?this.Yb=setInterval(s(this.Sb,this),1E3):this.F=g};
q.fa=function(){if(!this.G)this.G=g};q.M=m("F");q.N=function(){ad(this);return this.Ia};q.J=function(){return this.a.video.url||this.a.video.src};q.T=function(){return L};q.O=p("");q.aa=function(){return this.a.video.duration&&this.a.video.duration*1E3};q.H=function(){return!this.G?M:this.a.Ke?"s4":this.a.paused?"s3":"s2"};q.U=function(){return y(this.a.video.time)};q.S=p(-1);q.$=function(){ad(this);return this.Ha};q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:Sa(this.q)};q.Y=m("Da");
q.P=m("xa");q.Z=p("FP");Q.prototype.getStrategyName=Q.prototype.Z;Q.prototype.isReady=Q.prototype.M;Q.prototype.getTitle=Q.prototype.N;Q.prototype.getVideoPath=Q.prototype.J;Q.prototype.getContentType=Q.prototype.T;Q.prototype.getAdPosition=Q.prototype.O;Q.prototype.getTotalDuration=Q.prototype.aa;Q.prototype.getState=Q.prototype.H;Q.prototype.getCurrentPlayTime=Q.prototype.U;Q.prototype.getBitrate=Q.prototype.S;Q.prototype.getThumbnailPath=Q.prototype.$;Q.prototype.getPlayerType=Q.prototype.X;
Q.prototype.getAutoplayType=Q.prototype.Q;Q.prototype.getViewStartTime=Q.prototype.ba;Q.prototype.getSections=Q.prototype.Y;Q.prototype.getAuthors=Q.prototype.P;Q.verify=function(a){return window.flowplayer&&a.engine&&a.engine.engineName};function S(a){this.a=a;this.Jb=this.G=this.F=j;this.q=u();this.xa=this.Da=d;this.ga()}q=S.prototype;q.ga=function(){this.a.readyState>0&&this.ka();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.fa();this.a.addEventListener("canplay",v(this.ka,this));var a=v(this.fa,this);this.a.addEventListener("playing",a);this.a.addEventListener("webkitbeginfullscreen",a);this.a.addEventListener("webkitendfullscreen",v(this.ne,this))};q.ka=function(){this.F=g};q.fa=function(){this.G=g;this.Jb=j};
q.ne=function(){this.Jb=g};q.M=m("F");q.N=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};q.J=function(){return this.a.currentSrc||""};q.T=function(){return L};q.O=p("");q.aa=function(){return y(this.a.duration)};q.H=function(){return!this.G?M:this.a.ended||this.Jb&&this.a.currentTime==this.a.duration?"s4":this.a.paused||this.Jb?"s3":"s2"};q.U=function(){return y(this.a.currentTime)};q.S=p(-1);q.$=function(){return this.a.poster||""};q.X=k();
q.Q=function(){return this.a.autoplay?"auto":"man"};q.ba=function(){return Ua(this.q)};q.Y=m("Da");q.P=m("xa");q.Z=p("H5");S.prototype.getStrategyName=S.prototype.Z;S.prototype.isReady=S.prototype.M;S.prototype.getTitle=S.prototype.N;S.prototype.getVideoPath=S.prototype.J;S.prototype.getContentType=S.prototype.T;S.prototype.getAdPosition=S.prototype.O;S.prototype.getTotalDuration=S.prototype.aa;S.prototype.getState=S.prototype.H;S.prototype.getCurrentPlayTime=S.prototype.U;
S.prototype.getBitrate=S.prototype.S;S.prototype.getThumbnailPath=S.prototype.$;S.prototype.getPlayerType=S.prototype.X;S.prototype.getAutoplayType=S.prototype.Q;S.prototype.getViewStartTime=S.prototype.ba;S.prototype.getSections=S.prototype.Y;S.prototype.getAuthors=S.prototype.P;S.verify=function(a){var b=a instanceof HTMLElement&&a.nodeName==="VIDEO",a=a.getAttribute&&a.getAttribute("data-account")!==i;return b&&!a};function T(a){this.a=a;this.G=this.ya=this.F=j;this.q=u();this.bb=j;this.ga()}q=T.prototype;q.ga=function(){function a(a,f){f=s(f,c);if(aa(b.on)=="function")b.on(a,f);else{var h="on"+a.substr(0,1).toUpperCase()+a.substr(1);if(aa(b[h])=="function")b[h](f)}}var b=this.a,c=this;a("ready",this.ka);a("time",this.he);a("complete",this.ie);a("adStarted",this.va);a("adPlay",this.va);a("adImpression",this.va);a("adTime",this.va);a("adComplete",this.cc);a("adSkipped",this.cc);a("adError",this.cc)};
q.ka=function(){this.F=g};q.he=function(){this.ya=j;this.G=g;this.bb=j};q.ie=function(){this.ya=g};q.va=function(){this.bb=this.G=g};q.cc=function(){this.bb=j};q.M=function(){this.a.getState();return this.F||this.a.getState()!==d};q.N=function(){var a=bd(this);return!a?"":a.title};function bd(a){if(a.a.getPlaylistIndex===d)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}
q.J=function(){var a=bd(this);return!a?"":a.mediaid||a.file};q.T=function(){return this.bb?"ad":L};q.O=p("");q.aa=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};q.H=function(){if(!this.G)return M;if(this.bb)return"s2";if(this.ya)return"s4";var a=this.a.getState();return a&&a.toUpperCase()==="PAUSED"?"s3":"s2"};q.U=function(){var a=this.a.getPosition();return y(a)};q.S=p(-1);q.$=function(){var a=bd(this);return!a?"":a.image};q.X=k();q.ba=function(){return isNaN(this.q)?0:Sa(this.q)};
q.P=k();q.Y=k();q.Q=p("unkn");q.Z=p("JW");T.prototype.getStrategyName=T.prototype.Z;T.prototype.isReady=T.prototype.M;T.prototype.getTitle=T.prototype.N;T.prototype.getVideoPath=T.prototype.J;T.prototype.getContentType=T.prototype.T;T.prototype.getAdPosition=T.prototype.O;T.prototype.getTotalDuration=T.prototype.aa;T.prototype.getState=T.prototype.H;T.prototype.getCurrentPlayTime=T.prototype.U;T.prototype.getBitrate=T.prototype.S;T.prototype.getThumbnailPath=T.prototype.$;
T.prototype.getPlayerType=T.prototype.X;T.prototype.getViewStartTime=T.prototype.ba;T.prototype.getAuthors=T.prototype.P;T.prototype.getSections=T.prototype.Y;T.prototype.getAutoplayType=T.prototype.Q;T.verify=function(a){return w(a.id)&&w(a.registerPlugin)};function V(a){this.a=a;this.lb="";this.ca=M;this.pa=L;this.ja="";this.q=u();this.ga()}q=V.prototype;q.ga=function(){this.a.kBind("playerStateChange.cb",s(this.me,this));this.a.kBind("playerUpdatePlayhead.cb",s(this.ce,this));this.a.kBind("playerPlayEnd.cb",s(this.le,this));this.a.kBind("adStart.cb",s(this.va,this));this.a.kBind("adEnd.cb",s(this.bc,this));this.a.kBind("switchingChangeComplete.cb",s(this.ge,this))};
q.me=function(a){switch(a){case "playing":this.ca="s2";break;case "buffering":this.ca="s3";break;case "paused":this.ca="s3"}};q.ce=function(){this.ca="s2";this.a.kUnbind("playerUpdatePlayhead.cb")};q.le=function(){this.ca="s4"};q.va=function(a){this.pa="ad";switch(a){case "pre":this.ja="a1";break;case "post":this.ja="a3";break;case "mid":this.ja="a2";break;case "main":this.ja="a5"}};q.bc=function(){this.pa=L};q.ge=function(a,b){this.td=b};
q.M=function(){return this.a.evaluate("{mediaProxy.entry.name}")!=i};q.N=function(){return this.a.evaluate("{mediaProxy.entry.name}")};q.J=function(){if(!this.M())return this.lb;var a=this.a.evaluate("{mediaProxy.entry.id}");return(this.lb=a)||""};q.T=m("pa");q.O=m("ja");q.aa=function(){var a=this.a.evaluate("{duration}");return y(a)};q.H=m("ca");q.U=function(){var a=this.a.evaluate("{video.player.currentTime}");return y(a)};q.S=m("td");
q.$=function(){return this.a.evaluate("{mediaProxy.entry.thumbnailUrl}")||""};q.X=k();q.Q=function(){var a=this.a.evaluate("{configProxy.flashvars.autoPlay}"),b=this.a.evaluate("{configProxy.flashvars.playlistAPI.autoContinue}"),c=this.a.evaluate("{playlistAPI.dataProvider.selectedIndex}");return b&&c>0?"cont":a?"auto":"man"};q.ba=function(){return isNaN(this.q)?0:Ua(this.q)};q.Y=function(){var a=this.a.evaluate("{mediaProxy.entry.tags}");if(a)return a.split(",")};
q.P=function(){var a=this.a.evaluate("{mediaProxy.entry.creatorId}");if(a)return[encodeURIComponent(a)]};q.Z=p("KT");V.prototype.getStrategyName=V.prototype.Z;V.prototype.isReady=V.prototype.M;V.prototype.getTitle=V.prototype.N;V.prototype.getVideoPath=V.prototype.J;V.prototype.getContentType=V.prototype.T;V.prototype.getAdPosition=V.prototype.O;V.prototype.getTotalDuration=V.prototype.aa;V.prototype.getState=V.prototype.H;V.prototype.getCurrentPlayTime=V.prototype.U;V.prototype.getBitrate=V.prototype.S;
V.prototype.getThumbnailPath=V.prototype.$;V.prototype.getPlayerType=V.prototype.X;V.prototype.getAutoplayType=V.prototype.Q;V.prototype.getViewStartTime=V.prototype.ba;V.prototype.getSections=V.prototype.Y;V.prototype.getAuthors=V.prototype.P;V.verify=function(a){return typeof a.kBind=="function"};function W(a){this.a=a;this.F=j;this.ca=M;this.pa=L;this.ja=this.lb="";this.q=u();this.ga()}q=W.prototype;
q.ga=function(){this.a.addEventListener(this.a.Event.Core.PLAY,s(this.fa,this));this.a.addEventListener(this.a.Event.Core.PAUSE,s(this.ke,this));this.a.addEventListener(this.a.Event.Core.PLAYBACK_ENDED,s(this.je,this));this.a.addEventListener(this.a.Event.AD_BREAK_START,s(this.va,this));this.a.addEventListener(this.a.Event.AD_BREAK_END,s(this.bc,this));this.a.addEventListener(this.a.Event.Core.SOURCE_SELECTED,s(this.ka,this))};q.fa=function(){this.ca="s2"};q.ke=function(){this.ca="s3"};
q.je=function(){this.ca="s4"};q.M=function(){return this.F||this.a.config.sources.metadata&&this.a.config.sources.metadata.name};q.va=function(a){this.ca="s3";a=a.payload.adBreak.type;this.pa="ad";switch(a){case "preroll":this.ja="a1";break;case "postroll":this.ja="a3";break;case "midroll":this.ja="a2"}};q.bc=function(){this.pa=L};q.ka=function(){this.F=g};q.N=function(){return this.a.config.sources.metadata?this.a.config.sources.metadata.name:""};
q.J=function(){if(!this.M())return this.lb;var a=this.a.config.sources.id;return(this.lb=a)||""};q.T=m("pa");q.O=m("ja");q.aa=function(){if(typeof this.a.config.sources.duration!=="undefined")return y(this.a.config.sources.duration)};q.H=m("ca");q.U=function(){return y(this.a.currentTime)};q.S=k();q.$=function(){return this.a.poster};q.X=k();
q.Q=function(){var a=this.a.config.playback.autoplay,b=this.a.playlist._playlist._activeItemIndex;return this.a.playlist.options.autoContinue&&b>0?"cont":a?"auto":"man"};q.ba=function(){return isNaN(this.q)?0:Ua(this.q)};q.Y=function(){if(this.a.config.sources.metadata&&this.a.config.sources.metadata.tags.length)return this.a.config.sources.metadata.tags.split(", ")};q.P=k();q.Z=p("KT7");W.prototype.getStrategyName=W.prototype.Z;W.prototype.isReady=W.prototype.M;W.prototype.getTitle=W.prototype.N;
W.prototype.getVideoPath=W.prototype.J;W.prototype.getContentType=W.prototype.T;W.prototype.getAdPosition=W.prototype.O;W.prototype.getTotalDuration=W.prototype.aa;W.prototype.getState=W.prototype.H;W.prototype.getCurrentPlayTime=W.prototype.U;W.prototype.getBitrate=W.prototype.S;W.prototype.getThumbnailPath=W.prototype.$;W.prototype.getPlayerType=W.prototype.X;W.prototype.getAutoplayType=W.prototype.Q;W.prototype.getViewStartTime=W.prototype.ba;W.prototype.getSections=W.prototype.Y;
W.prototype.getAuthors=W.prototype.P;W.verify=function(a){return a.Event&&a.Event.Core};function X(a){this.zc=d;this.a=a;this.Mc=d;this.F=j;this.Ka=d;this.G=j;this.xa=this.Da=this.q=d;this.zc=r.OO;this.Mc=this.a.mb;this.q=u();this.ga()}q=X.prototype;
q.ga=function(){var a=this.Mc,b=this.zc.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.ka,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.Sd,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.fa,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.Rd,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.be,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Xd,this))};q.ka=function(){this.F=g};
q.Sd=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.Ka=a===0?"a1":cd(a,b)?"a3":"a2"};q.fa=function(){this.G=g};q.Rd=function(){this.Ka=d};q.be=k();q.M=function(){var a=this.a.getState();if(a==="ready"||a==="playing"||a==="paused")this.F=g;return this.F};q.N=function(){var a=this.a.getItem();return a?a.title:""};
q.J=function(){var a=this.a.getEmbedCode&&this.a.getEmbedCode();if(a)return a;a=this.a.getItem()||{};return a.embed_code||a.embedCode||this.a.embedCode||""};q.T=function(){return this.Ka===d?L:"ad"};q.O=function(){return this.Ka?this.Ka:""};q.aa=function(){var a=this.a.getItem(),a=a&&a.duration||this.a.getDuration()*1E3;return a===-1||!isFinite(a)?-1:a};
q.H=function(){if(!this.G)return M;if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return cd(a,b)?"s4":"s2"};function cd(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}q.Xd=function(){this.Ka=d};q.U=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};
q.S=function(){var a=this.a.getCurrentBitrate&&this.a.getCurrentBitrate();return a?a.bitrate:0};q.$=function(){var a=this.a.getItem();return!a?"":a.promo||a.promo_image||a.thumbnail_image};q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:Ua(this.q||0)};q.Y=m("Da");q.P=m("xa");q.Z=p("OO");X.prototype.getStrategyName=X.prototype.Z;X.prototype.isReady=X.prototype.M;X.prototype.getTitle=X.prototype.N;X.prototype.getVideoPath=X.prototype.J;X.prototype.getContentType=X.prototype.T;
X.prototype.getAdPosition=X.prototype.O;X.prototype.getTotalDuration=X.prototype.aa;X.prototype.getState=X.prototype.H;X.prototype.getCurrentPlayTime=X.prototype.U;X.prototype.getBitrate=X.prototype.S;X.prototype.getThumbnailPath=X.prototype.$;X.prototype.getPlayerType=X.prototype.X;X.prototype.getAutoplayType=X.prototype.Q;X.prototype.getViewStartTime=X.prototype.ba;X.prototype.getSections=X.prototype.Y;X.prototype.getAuthors=X.prototype.P;
X.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("isAdPlaying")};function Y(a){this.a=a;this.ia=i;this.$a="";this.ca=M;this.pa=L;this.ja="";this.q=u();this.a.controller.plugInLoaded&&this.a.controller.plugInLoaded(this)}q=Y.prototype;q.Nd=function(a){this.ga(a.controller)};
q.ga=function(a){a.addEventListener("OnLoadRelease",v(this.Rc,this));a.addEventListener("OnLoadReleaseUrl",v(this.Rc,this));a.addEventListener("OnReleaseStart",v(this.ee,this));a.addEventListener("OnMediaPlay",v(this.Zd,this));a.addEventListener("OnMediaStart",v(this.ae,this));a.addEventListener("OnMediaPause",v(this.fc,this));a.addEventListener("OnMediaComplete",v(this.Yd,this));a.addEventListener("OnMediaError",v(this.fc,this));a.addEventListener("OnMediaBuffer",v(this.fc,this));a.addEventListener("OnMediaPlaying",
v(this.$d,this))};q.Rc=function(a){if(a.data&&a.data.title)this.ia=a.data;if(a.data&&a.data.guid)this.$a=a.data.guid};q.ee=function(a){t(a.data.clips,v(function(a){if(a=a.baseClip.guid)return this.$a=a,j},this));if(this.$a&&a.data.release&&a.data.release.title)this.ia=a.data.release};q.Zd=function(){this.ca="s2"};q.ae=function(a){this.ca="s2";a=a.data.baseClip;a.isAd?(this.pa="ad",this.ja=a.isMid?"a2":"a1"):(this.pa=L,this.ja="")};q.fc=function(){if(this.ca!=M)this.ca="s3"};
q.Yd=function(){this.ca="s4"};q.$d=function(a){this.xd=a.currentTime};q.M=function(){return this.ia!=i};q.N=function(){return this.ia.title};q.J=function(){return!this.$a?"":this.$a};q.T=m("pa");q.O=m("ja");q.aa=function(){return this.ia.duration};q.H=m("ca");q.U=m("xd");q.S=function(){return this.ia.bitrate};q.$=function(){return this.ia&&this.ia.defaultThumbnailUrl?this.ia.defaultThumbnailUrl:this.ia.pid?"http://link.theplatform.com/s/ngc/"+this.ia.pid+"?format=poster&height=70&width=95":""};
q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:this.q===d?0:u()-this.q};q.Y=function(){var a=this.ia.keywords?this.ia.keywords.split(","):[],b=[];t(this.ia.categories?this.ia.categories:[],function(a){b.push(encodeURIComponent(a.name))});t(a,function(a){b.push(encodeURIComponent(a.trim()))});return b};q.P=k();q.Z=p("TP");Y.prototype.initialize=Y.prototype.Nd;Y.prototype.getStrategyName=Y.prototype.Z;Y.prototype.isReady=Y.prototype.M;Y.prototype.getTitle=Y.prototype.N;
Y.prototype.getVideoPath=Y.prototype.J;Y.prototype.getContentType=Y.prototype.T;Y.prototype.getAdPosition=Y.prototype.O;Y.prototype.getTotalDuration=Y.prototype.aa;Y.prototype.getState=Y.prototype.H;Y.prototype.getCurrentPlayTime=Y.prototype.U;Y.prototype.getBitrate=Y.prototype.S;Y.prototype.getThumbnailPath=Y.prototype.$;Y.prototype.getPlayerType=Y.prototype.X;Y.prototype.getAutoplayType=Y.prototype.Q;Y.prototype.getViewStartTime=Y.prototype.ba;Y.prototype.getSections=Y.prototype.Y;
Y.prototype.getAuthors=Y.prototype.P;Y.verify=function(a){return typeof a.controller!=="undefined"};function dd(a,b){this.a=a;this.dd=b;this.Na=window.location!=window.parent.location;this.Uc=j;this.xe=u();this.cd="_v_";this.ta={};gc.call(this)}ea(dd,gc);var ed=r.QUICK_TEST?1E4:6E4,fd="autoDetect",gd={Ge:"title",He:"videopath",Fe:"thumbnailpath"},hd={};q=dd.prototype;
q.da=function(){this.$b=(this.Sa=this.B.D("_chartbeat3"))?0:1;this.vc=this.oc=g;this.Pb=j;this.Eb=this.kc=this.Fc=this.Ga=d;this.La=15E3;this.pb=d;this.qb=this.rb=0;this.Qb=j;this.pe=this.tc=this.Ib=0;this.lc=j;if(!this.Sa||this.Sa.length===0)this.Sa=pa(ic(this),3);this.B.create("_chartbeat3",this.Sa,34128E3);var a;(a=this.dd)&&La(a)?(this.ha=new a(this.a),a=g):a=j;if(a){a=!!this.k[Mb];var b=Zb(!!this.k[Nb]&&a);F(this.k,"pingServer","ping.chartbeat.net");F(this.k,Ob,document.title);F(this.k,C,b);
this.k[B]=this.k[B]?J(this.k[B]):Xb(a);this.k[C]=x(this.k[C]);this.ha.getPlayerType&&F(this.k,"video_type",this.ha.getPlayerType());this.Fc=setInterval(v(this.ud,this),1E3);if(this.Na===g)this.zb=v(this.Id,this),Ha(window,"message",this.zb),this.pb=setInterval(this.qe,1E3);dd.la.da.call(this)}};q.Mb=k();
q.qa=function(){if(this.ha){if(!id(this))this.vc=g;if(!this.vc)return u()-this.Ua>=this.yb&&clearInterval(this.Ga),dd.la.qa.call(this);if(this.ha.isReady())this.Pb=this.vc=j,this.kc=jd(this),kd(this),this.Ga=setInterval(v(this.Ob,this),100),dd.la.qa.call(this);else if(!this.Pb){this.Pb=g;if(this.pe++>150)throw"Error: Video strategy never reported its ready state";ld(this,100)}}};
q.Ca=function(){if(this.ha){var a=this.k,b=this.ha,c=b.getState(),e=id(this),f=this.Na?[]:r._cbq||(r._cbq=[]),h=b.getViewStartTime(),l=md(this),o=b.getAutoplayType?b.getAutoplayType():d,h=h===-1?-1:h/1E3,l=l?encodeURIComponent(l):d;if(!hd.path||hd.path===e||c==="s2"&&hd.state!=="s2")switch(hd={path:e,state:c},f.push(["_vi",Na(nd(this))]),f.push(["_vp",e]),f.push(["_vdd",Na(od(this))]),f.push(["_vs",b.getState()]),b.getContentType&&f.push(["_vt",b.getContentType()]),b.getAdPosition&&f.push(["_vap",
b.getAdPosition()]),f.push(["_vtn",Na(md(this))]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case M:case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}a=pd(this)+Z("_vt",b.getContentType?b.getContentType():"")+Z("_vap",b.getAdPosition?b.getAdPosition():"")+Z("_vs",c)+Z("_vcs",this.Qb?"1":"0")+Z("_vbr",b.getBitrate?b.getBitrate():"")+Z("_vvs",h)+Z("_vpt",b.getCurrentPlayTime())+Z("_vtn",l)+Z("_vaup",o||"unkn")+Z("_vplt",a.video_type)+Z("_vce",this.tc)+Z("c",Math.round(Sa(this.xe)/
600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.Ib+"&j="+(this.La/1E3+15)+qd(this)+"&tz="+(new Date).getTimezoneOffset()+(Wb(this.B)?"&l=1":"")+"&_";this.Na===g&&t(f,function(a){window.top.postMessage("cbqpush::"+a.join("::"),"*")});this.ib(a)}};function Z(a,b){return b!==d&&b!==""?"&"+a+"="+b:""}q.fb=function(){this.B.update("_cb_cp",this.Ea,60,j,",")};function qd(a){var b=a.B.D("_cb_cp");a.B.remove("_cb_cp");return b?"&D="+b:""}
function rd(a){return a.k.subdomain?a.k.subdomain:x(r.location.hostname)}function od(a){var b=a.k,a=a.ha,b=b.videodomain||a.getHost&&a.getHost()||b[C];return"video@"+(b&&b.replace(/^video@/,""))}function id(a){var b=a.ta.videopath;if(b)return b;if(a.k.videoPathHash){if(a=nd(a))return pa(a)}else return a.ha.getVideoPath();return""}function nd(a){return a.ta.title||a.ha.getTitle()}function md(a){return a.ta.thumbnailpath||a.ha.getThumbnailPath()}
function pd(a){var b=a.k,c=a.ha,e=c.getUid&&c.getUid()||b.uid,f=Na(od(a)),h="",l=a.gb?"&b="+a.gb:"",o,n=a.k[B];o=a.k.useSubDomains!==j&&n&&n.substr(0,1)==="/"?rd(a)+n:n;var n=c.getSections&&c.getSections(),D=c.getAuthors&&c.getAuthors(),G=b.sections?"&g0="+encodeURIComponent(b.sections):"",R=b.authors?"&g1="+encodeURIComponent(b.authors):"",n=n===d||b.videoPageGroups?G:"&g0="+encodeURIComponent(n.join(",")),D=D===d||b.videoPageGroups?R:"&g1="+encodeURIComponent(D.join(",")),R="",G=id(a);if(a.Eb===
d)a.Eb=G;else if(G!=a.Eb)R=Z("D",a.Ea),a.Ea=pa(ic(a)),a.Eb=G,a.rb=0,a.qb=0,a.Ib=0,a.tc=0,a.Qb=sd(a)&&!td(a),a.oc=g;if(a.oc||R){if(a.Na===j||a.Na===g&&a.Uc===g)a.oc=j;h=(jc(a)?"&v=":"&r=")+kc(a)}a.Ib+=a.rb;a.rb=0;a.tc+=a.qb;a.qb=0;kd(a);var U=G="",ha="",ca="",N="",E="",ja="",ka="";if(!a.Na===g||a.lc===g)G="&_vi="+qc(a),U="&_vp="+encodeURIComponent(o),ha="&_vh="+Na(rd(a)),ca="&_vdd="+encodeURIComponent(b[C]),a.lc===g?(N=b.u,E=b.t,ja=cb(b.v),ka=cb(b.r)):(N=dc("u"),E=dc("t"),ja=cb(dc("v")),ka=cb(dc("r")));
o="";o=Ka(ja)?"&_pv="+ja:Ka(ka)?"&_pr="+ka:"&_pr=NA";ja="&_pu=";ka="&_pt=";ja+=N?N:"NA";ka+=E?E:"NA";N=!b.noCookies&&a.B.isSupported();E=c.getStrategyName?c.getStrategyName():"";return Oa()+"//"+b.pingServer+"/ping?h="+f+"&g="+e+"&p="+Na(id(a))+"&i="+Na(nd(a))+n+D+"&u="+a.Sa+"&t="+a.Ea+"&x=0&y=0&V=120"+Z("VS",E)+(N?"&n="+a.$b:"&nc=1")+l+h+R+Z("_vd",c.getTotalDuration())+G+U+ha+ja+ka+o+ca}q.Ob=function(){if(sd(this)&&!td(this))this.Qb=g;var a=jd(this);if(this.kc!=a)this.kc=a,kd(this),this.qa()};
function kd(a){var b=a.La;a.La=sd(a)?a.Ib<60?5E3:15E3:ed;b!=a.La&&ld(a,a.La)}function ld(a,b){clearInterval(a.ub);a.La=b;a.ub=setInterval(v(a.qa,a),b)}function jd(a){return a.ha.getState()+a.ha.getContentType()}function sd(a){return a.ha.getState()==="s2"||td(a)}function td(a){return a.ha.getContentType()==="ad"}q.ud=function(){sd(this)===g&&(this.rb+=1,this.ha.getContentType()===L&&(this.qb+=1))};q.qe=function(){window.parent.postMessage("cbdata?","*")};
q.Id=function(a){if(a.source===window.parent&&(a=a.data,Ka(a)&&a.indexOf("domain=")===0)){this.lc=g;var b={domain:g,uid:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g,u:g,t:g,v:g,r:g},c=this;t(a.split("&"),function(a){var a=a.split("="),f=a[0],a=a[1];b[f]&&(c.k[f]=decodeURIComponent(a))});Ia(window,"message",this.zb);clearInterval(this.pb);this.pb=d;this.Uc=g;this.qa()}};q.setProperty=function(a,b){var c=j,e=this;t(gd,function(f){if(a.toLowerCase()==f)return e.ta[f]=b,c=g,j});return c};
q.terminate=function(){clearInterval(this.Fc);clearInterval(this.pb);clearInterval(this.Ga);Ia(window,"message",this.zb);dd.la.terminate.call(this)};q.Aa=function(){dd.la.Aa.call(this);this.dd=this.a=this.zb=i};function $(a){this.a=a;this.F=g;this.G=j;this.q=u();this.Ga=this.xa=this.Da=d;this.ga()}q=$.prototype;q.ga=function(){this.Ga=setInterval(s(this.Ob,this),100);var a=this.a.getPlayerState();(a===1||a===2||a===0)&&this.fa()};q.Ob=function(){if(this.a.getPlayerState()===1)clearInterval(this.Ga),this.Ga=d,this.fa()};q.fa=function(){if(!this.G)this.G=g};function Ed(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}q.M=m("F");
q.N=function(){var a="";La(this.a.getVideoData)&&(a=(a=this.a.getVideoData())&&a.title||"");return a};q.J=function(){return Ed(this)||this.a.getVideoUrl()};q.T=function(){return L};q.O=p("");q.aa=function(){var a=this.a.getDuration();return Ja(a)?a*1E3:a};q.H=function(){if(!this.G)return M;var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};q.U=function(){var a=this.a.getCurrentTime();return y(a)};q.S=p(-1);q.$=function(){return"http://img.youtube.com/vi/"+Ed(this)+"/default.jpg"};
q.X=k();q.Q=k();q.ba=function(){return isNaN(this.q)?0:Sa(this.q)};q.Y=m("Da");q.P=m("xa");q.Z=p("YT");$.prototype.getStrategyName=$.prototype.Z;$.prototype.isReady=$.prototype.M;$.prototype.getTitle=$.prototype.N;$.prototype.getVideoPath=$.prototype.J;$.prototype.getContentType=$.prototype.T;$.prototype.getAdPosition=$.prototype.O;$.prototype.getTotalDuration=$.prototype.aa;$.prototype.getState=$.prototype.H;$.prototype.getCurrentPlayTime=$.prototype.U;$.prototype.getBitrate=$.prototype.S;
$.prototype.getThumbnailPath=$.prototype.$;$.prototype.getPlayerType=$.prototype.X;$.prototype.getAutoplayType=$.prototype.Q;$.prototype.getViewStartTime=$.prototype.ba;$.prototype.getSections=$.prototype.Y;$.prototype.getAuthors=$.prototype.P;$.verify=function(a){return La(a.getDuration)&&La(a.getVideoUrl)&&La(a.getVideoEmbedCode)};function Fd(){r._cbv_strategies||(r._cbv_strategies=[]);r._cbv_strategies.push(X);r._cbv_strategies.push(S);r._cbv_strategies.push(Q);r._cbv_strategies.push($);r._cbv_strategies.push(T);r._cbv_strategies.push(P);r._cbv_strategies.push(O);r._cbv_strategies.push(V);r._cbv_strategies.push(W);r._cbv_strategies.push(Y);this.uc=[];this.ta=[];this.k=r._sf_async_config||{};Qb("_cbv",v(this.Jd,this));if(this.k[fd]!==j)this.Bd=ab(v(this.Ic,this),5E3),this.Ic(),setTimeout(v(this.wa,this),3E4)}
Fd.prototype.Jd=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){Gd();return}else if(b==="removePlayer"){Hd(this,a[1]);return}else if(b==="setProps"){Id(a[1])||this.ta.push(a[1]);return}}Jd(this,a)};function Kd(){if(La(window.videojs)&&La(window.videojs.plugin))try{return window.videojs.plugin("chartbeat",function(a){this.cb_configs=a;window._cbv.push(this)}),g}catch(a){}return j}
function Jd(a,b){var c=j,e=r._cbv_strategies;w(window.jwplayer)&&(b=La(b)?b():b);t(e,function(a){if(a.verify(b))return c=a,j});c&&Ld(a,b,c)}function Hd(a,b){var c=a.uc,e=r.pSUPERFLY_video,f=Qa(c,function(a){return b===a});f!==-1&&c.splice(f,1);f=Qa(e,function(a){return a.a===b});f!==-1&&e.splice(f,1)[0].Aa()}function Id(a){if(!w(a))return j;var b=a.player,c=Ra(function(a){return a.a===b});return!w(c)?j:Md(c,a)}
function Md(a,b){var c=j;t(b,function(b,f){if(f!=="player"&&(c=a.setProperty(f,b),!c))return c});return c}function Ld(a,b,c){var e=j;t(a.uc,function(a){if(b===a)return e=g,j});if(!e){c=new dd(b,c);r.pSUPERFLY_video.push(c);for(var f=a.ta.length-1;f>-1;f--)Md(c,a.ta[f])&&a.ta.splice(f,1);c.nb();a.uc.push(b)}}
Fd.prototype.Ic=function(){if(La(window.jwplayer)&&w(window.jwplayer())){this.wa();for(var a=0,b=window.jwplayer(a);w(b.id);)window._cbv.push(b),b=window.jwplayer(++a)}else{if(window.flowplayer&&(a=window.flowplayer())){this.wa();window._cbv.push(a);return}window.brightcove&&window.experienceJSON?(this.wa(),window._cbv.push(window.brightcove)):Kd()?this.wa():window.kWidget?(this.wa(),window.kWidget.addReadyCallback(function(a){window._cbv.push(document.getElementById(a))})):window.$pdk?(this.wa(),
window._cbv.push(window.$pdk)):window.KalturaPlayer&&La(window.KalturaPlayer.getPlayers)?(this.wa(),a=window.KalturaPlayer.getPlayers(),t(a,function(a){window._cbv.push(a)})):t(document.getElementsByTagName("video"),function(a){window._cbv.push(a)})}};Fd.prototype.wa=function(){Ya(this.Bd)};
function Gd(){function a(){function a(b){r._cbv.push(b.target)}var b=r.YT.Player;t(document.getElementsByTagName("iframe"),function(f){var h=f.src,l=h&&h.indexOf("www.youtube.com/embed/");h&&l>=0&&l<9&&new b(f,{events:{onReady:a}})})}if(r.YT&&r.YT.Player)a();else{var b=r.onYouTubeIframeAPIReady;r.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(r,arguments)}catch(c){}a()}}}};function Nd(a,b){return function(c,e){if(!Db){a();var f=r._sf_async_config,h="",l=f[B],l=ta(l);/^\//.test(l)&&(h=x(r.location.hostname));f[Pb]=Oa()+"//"+h+l;if(Ka(c))f[B]=J(c),e&&(f[Ob]=e);else if(Pa(c)){var o=["authors","sections",Ob,B,Pb];t(c,function(a,b){if(Qa(o,function(a){return a===b})!==-1||b.indexOf("_")===0)f[b]=b===B?J(a):a})}b()}}};if(!H.D("cb_optout")){if(window.location==window.parent.location&&!r.pSUPERFLY){var Od=new Uc,Pd={};r.pSUPERFLY=Pd;var Qd=!!Jc;Pd.virtualPage=Nd(function(){Od.sb();Qd&&Jc.evps()},function(){Od.Fb();Qd&&Jc.svps()});Pd.activity=v(Od.ld,Od);Od.nb();Pc.exec(document.referrer)&&Rc();var Rd=I.ea(g);if(!Rd?0:Rd.getItem("_cb_ip")){var Sd=r.location;(!/^(.+[.])?chartbeat\.com$/.test(Sd.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Sd.pathname))||ub(Qc)}else Ha(r,"message",Sc)}r.pSUPERFLY_video||(r.pSUPERFLY_video=
[]);new Fd};})();
