apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    app: kuard
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 31001
    protocol: TCP
  selector:
    app: kuard
