apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra-snap
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra-snap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: px/running
                operator: NotIn
                values:
                - "false"
              - key: px/enabled
                operator: NotIn
                values:
                - "false"
      containers:
      - name: cassandra
        image: cassandra:9.5
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        env:
        - name: cassandra_USER
          value: pgbench
        - name: PGUSER
          value: pgbench
        - name: cassandra_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cassandra-pass
              key: password.txt
        - name: PGBENCH_PASSWORD
          value: supercassandra
        - name: PGDATA
          value: /var/lib/cassandraql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/cassandraql/data
          name: postgredb
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: px-cassandra-snap-clone
