apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: px-cassandra-snap-clone
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: px-cassandra-snapshot
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 2Gi
