---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: mcrouter-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - '*'
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - apps
    resourceNames:
      - mcrouter-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - memcached.example.com
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - mcrouter.example.com
    resources:
      - '*'
      - mcrouters
    verbs:
      - '*'

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mcrouter-operator
subjects:
  - kind: ServiceAccount
    name: mcrouter-operator
roleRef:
  kind: Role
  name: mcrouter-operator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcrouter-operator

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcrouter-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mcrouter-operator
  template:
    metadata:
      labels:
        name: mcrouter-operator
    spec:
      serviceAccountName: mcrouter-operator
      containers:
        - name: ansible
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          image: "geerlingguy/mcrouter-operator:0.2.2"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
          securityContext:
            privileged: true
        - name: operator
          image: "geerlingguy/mcrouter-operator:0.2.2"
          imagePullPolicy: "Always"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mcrouter-operator"
      volumes:
        - name: runner
          emptyDir: {}

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mcrouters.mcrouter.example.com
spec:
  group: mcrouter.example.com
  names:
    kind: Mcrouter
    listKind: McrouterList
    plural: mcrouters
    singular: mcrouter
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha3
  versions:
    - name: v1alpha3
      served: true
      storage: true