apiVersion: v1
kind: Pod
metadata:
  name: es
  labels:
    app: es
    tier: backend
spec:
  containers:
  - name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    env:
      - name: discovery.type
        value: single-node
    ports:
    - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    app: es
    tier: backend
---
