apiVersion: broker.amq.io/v2alpha3
kind: ActiveMQArtemis
metadata:
  name: broker
  namespace: messaging
spec:
  acceptors:
    - name: amqp
      port: 5672
      protocols: amqp
      expose: true
  console:
    expose: true
  deploymentPlan:
    image: 'registry.redhat.io/amq7/amq-broker:7.7'
    size: 1
