apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    config:
      num.partitions: 1
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
    replicas: 1
    listeners:
      plain: {}
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
