apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: ghost
    app-purpose: chaos
    kube-monkey/enabled: enabled
    kube-monkey/identifier: "frontend"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "1"
  name: ghost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
        app-purpose: chaos
        kube-monkey/enabled: enabled
        kube-monkey/identifier: "frontend"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        kube-monkey/mtbf: "1"
    spec:
      containers:
      - image: ghost:3.11.0-alpine
        imagePullPolicy: Always
        name: ghost
