apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: nginx
    app-purpose: chaos
    kube-monkey/enabled: enabled
    kube-monkey/identifier: "frontend"
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
    kube-monkey/mtbf: "1"
  name: nginx
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        app-purpose: chaos
        kube-monkey/enabled: enabled
        kube-monkey/identifier: "frontend"
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        kube-monkey/mtbf: "1"
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
