apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: env-context
spec:
  selector:
    matchLabels:
      role: frontend
    env:
      - name: SERVER_REDIRECT
        value: "kubernetes.io/docs/concepts/workloads/pods/podpreset/"
