apiVersion: charts.helm.k8s.io/v1alpha1
kind: Cockroachdb
metadata: 
  name: example
spec: 
  statefulset: 
    replicas: 1
  storage: 
    persistentVolume: 
      size: 1Gi
      storageClass: local-storage
