apiVersion: v1
kind: Pod
metadata:
  name: kuard-secretive
spec:
  containers:
    - name: kuard-tls
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: creds
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: creds
              key: password
  volumes:
    - name: creds
      secret:
        secretName: db-creds
  