apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: nodejs-ex-image
  labels:
    app: tekton-workshop
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/lab-tekton/nodejs-ex:latest
