apiVersion: v1
kind: Pod
metadata:
  name: crasher
  labels:
    app: crasher
spec:
  restartPolicy: Always
  containers:
    - name: container-a
      image: chentex/random-logger
      livenessProbe:
        initialDelaySeconds: 3
        periodSeconds: 10
        failureThreshold: 1
        successThreshold: 1
        tcpSocket:
          port: 80
        timeoutSeconds: 2
