kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: mq-data
   annotations:
     volume.beta.kubernetes.io/storage-class: px-mq-sc
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi