apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    app: goodbad
  name: goodbad
spec: {}
status:
  dockerImageRepository: ""
---
apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: goodbad
  name: goodbad
spec:
  output:
    to:
      kind: ImageStreamTag
      name: goodbad:latest
  resources: {}
  source:
    contextDir: labs/lab-04/exercise-03
    git:
      uri: https://github.com/fatherlinux/container-internals-lab
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: httpd-php:latest
    type: Docker
  triggers:
  - github:
      secret: Jxx_nqGTx19G0fHE9o4U
    type: GitHub
  - generic:
      secret: FCvPlf890_pHVDC-YAuM
    type: Generic
  - type: ConfigChange
  - type: imageChange
    imageChange: {}
