apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: ghost
    app-purpose: chaos
  name: ghost
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
        app-purpose: chaos
    spec:
      containers:
      - image: ghost:3.11.0-alpine
        name: ghost
