kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-postgres-pvc
spec:
   storageClassName: px-repl3-sc
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
