apiVersion: v1
kind: Service
metadata:
  name: $APP_NAME
spec:
  ports:
  - name: web
    nodePort: 32500
    port: 8080
    protocol: TCP
  selector:
    app: $APP_NAME
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $APP_NAME
  labels:
    app: $APP_NAME
spec:
  selector:
    matchLabels:
      app: $APP_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $REGISTRY/$APP_NAME:latest
        ports:
          - containerPort: 8080
